---
# tasks file for ansible-role-mod-php

- name: Assertions
  assert:
    that:
        - ansible_os_family == 'Debian'

- name: APT install
  apt:
      name: libapache2-mod-php5
      state: present
      update_cache: yes
      cache_valid_time: 3600

- name: Enable PHP module
  apache2_module:
      name: php5
      state: present
  notify:
      - Restart Apache
